wip
modernise for .net core, nullable, exit early, write build-info
build updates/customisations to handle Articulate folder structure,

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -10,7 +10,7 @@ jobs:
   build:
 
     runs-on: windows-latest
-    
+
     env:
       Solution_File: src\Articulate.sln
       Code_CSProj_File: src\Articulate\Articulate.csproj
@@ -18,20 +18,30 @@ jobs:
       Release_Folder: build\Release
       Build_Folder: build
       Configuration: Release
-      
+
     steps:
     - name: Checkout
       uses: actions/checkout@v4
       with:
-        fetch-depth: 0    
+        fetch-depth: 0
     - uses: dotnet/nbgv@master
       with:
         setAllVars: true
-    - run: echo "NBGV_SemVer2 $NBGV_SemVer2"
+
+    - name: Log Build Context
+      run: |
+          echo "Articulate Build Context"
+          echo "Version: $NBGV_SemVer2"
+          echo "Commit: $NBGV_GitCommitIdShort"
+          echo "Date: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
+
+    - name: Validate Git Tag
+      run: |
+        git describe --tags --exact-match || echo "Git tag missing, release build may not be traceable."
 
     - name: Add MSBuild to PATH
       uses: microsoft/setup-msbuild@v2
-    
+
     - uses: nuget/setup-nuget@v2.0.1
       with:
         nuget-version: 'latest'
@@ -44,16 +54,16 @@ jobs:
 
     - name: Nuget Restore
       run: nuget restore $env:Solution_File
-    
+
     - name: MSBuild Clean
       run: msbuild $env:Solution_File /p:Configuration=${{ env.Configuration }} /t:Clean
-    
+
     - name: MSBuild Build
       run: msbuild $env:Solution_File /p:Configuration=${{ env.Configuration }}
 
     - name: Dotnet Pack
       run: dotnet pack ${{ env.Code_CSProj_File }} --output ${{ env.Release_Folder }} --configuration ${{ env.Configuration }}
-      
+
     - uses: actions/upload-artifact@v4
       with:
         name: Articulate.${{ env.NBGV_SemVer2 }}
